### PR TITLE
Migrate track files from v3-files

### PR DESCRIPTION
**Pull request by SaschaMann**
cc @exercism/python (This will not change or break anything, it merely copies them)

### CODE REVIEW

**Comment by SaschaMann** [comment]
The sudoku files should probably be moved to a different folder as that exercise is also in prob-specs and used by other tracks.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> The sudoku files should probably be moved to a different folder as that exercise is also in prob-specs and used by other tracks.

Maybe an exercises dir?

**Comment by SaschaMann** [comment]
> Maybe an exercises dir?

Whatever works for you and Jeremy.

**Comment by ErikSchierboom** [comment]
No that's fine, as they're in different sub-directories.

**Pull request merged**
