### PR TITLE
[queen-attack] Chess board SVG image

### PR DESCRIPTION
**Pull request by habere-et-dispertire**
Compressed and validated.

### CODE REVIEW

**Comment by IsaacG** [comment]
Out of curiosity, where did the base image come from and is there any licensing/copyright issues? Is an attribution needed?

**Comment by habere-et-dispertire** [comment]
> Out of curiosity, where did the base image come from and is there any licensing/copyright issues? Is an attribution needed?

See : https://github.com/exercism/problem-specifications/pull/2284#issuecomment-1579089178

**Comment by habere-et-dispertire** [comment]
## Preview

queen-capture-preview-min

**Comment by iHiD** [comment]
It would be nice if the labels were both chess notification and indexing. So maybe we could have A-H across the bottom, 1-8 up the side, and the indexes in brackets. 

e.g.
```
A (0)     B (1)      C (2)
```

And then we can add a note to the prob-specs description explaining that.

**Comment by iHiD** [comment]
I give you a screenshot from a recent game of mine as evidence ;) 

Screenshot 2023-06-05 at 01 37 45

**Comment by habere-et-dispertire** [comment]
Well spotted !
👓👍

diff-min

Let me know if I should close and reopen this PR to get the files through :

https://github.com/exercism/images/commit/e8b134a366aa45a0be169f1126aed17e5e9ce1b1

**Comment by iHiD** [comment]
Yeah, they can then play f6 to block, but then I can fork the king/queen with the knight on f6, so they have to take with the rook, and then I take the rook, but their position totally collapses. In the game they pushed their g-pawn forward to give me a check, but that didn't do much other than delay the inevitable :)

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
